<?xml version="1.0" encoding="utf-8"?><Database Name="GitLogAggregatorDB" Class="GitLogAggregatorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SOKKIMTHANH;Initial Catalog=GitLogAggregatorDB;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="GitLogAggregatorDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ProjectWeeks" Member="ProjectWeeks">
    <Type Name="ProjectWeek">
      <Column Name="ProjectWeekId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ConfigFileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InternshipDirectoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ProjectWeek_Commit" Member="Commits" ThisKey="ProjectWeekId" OtherKey="ProjectWeekId" Type="Commit" />
      <Association Name="ConfigFile_ProjectWeek" Member="ConfigFile" ThisKey="ConfigFileId" OtherKey="ID" Type="ConfigFile" IsForeignKey="true" />
      <Association Name="InternshipDirectory_ProjectWeek" Member="InternshipDirectory" ThisKey="InternshipDirectoryId" OtherKey="ID" Type="InternshipDirectory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Commits" Member="Commits">
    <Type Name="Commit">
      <Column Name="CommitId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommitHash" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="CommitMessage" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CommitDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectWeekId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Commit_ChatbotSummary" Member="ChatbotSummaries" ThisKey="CommitId" OtherKey="CommitId" Type="ChatbotSummary" />
      <Association Name="ProjectWeek_Commit" Member="ProjectWeek" ThisKey="ProjectWeekId" OtherKey="ProjectWeekId" Type="ProjectWeek" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ConfigFiles" Member="ConfigFiles">
    <Type Name="ConfigFile">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectDirectory" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="InternshipDirectoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Weeks" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstCommitDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ConfigFile_ProjectWeek" Member="ProjectWeeks" ThisKey="ID" OtherKey="ConfigFileId" Type="ProjectWeek" />
      <Association Name="InternshipDirectory_ConfigFile" Member="InternshipDirectory" ThisKey="InternshipDirectoryId" OtherKey="ID" Type="InternshipDirectory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChatbotSummary" Member="ChatbotSummaries">
    <Type Name="ChatbotSummary">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommitId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Attendance" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="AssignedTasks" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ContentResults" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SupervisorComments" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Commit_ChatbotSummary" Member="Commit" ThisKey="CommitId" OtherKey="CommitId" Type="Commit" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InternshipDirectories" Member="InternshipDirectories">
    <Type Name="InternshipDirectory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InternshipWeekFolder" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="InternshipDirectory_ProjectWeek" Member="ProjectWeeks" ThisKey="ID" OtherKey="InternshipDirectoryId" Type="ProjectWeek" />
      <Association Name="InternshipDirectory_ConfigFile" Member="ConfigFiles" ThisKey="ID" OtherKey="InternshipDirectoryId" Type="ConfigFile" />
    </Type>
  </Table>
</Database>